
FROM node:23-slim AS builder
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --legacy-peer-deps

COPY . .
RUN npm run build


FROM node:23-slim AS runner
WORKDIR /app

# Copy only necessary files for running the app
COPY --from=builder /app/package.json ./
COPY --from=builder /app/package-lock.json ./
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

# Install only production dependencies
RUN npm ci --omit=dev --legacy-peer-deps

# (Optional) Use non-root user for security
# RUN adduser --disabled-password appuser && chown -R appuser /app
# USER appuser

EXPOSE 3000

# Use the generated entry point from the standalone build
CMD ["node", "server.js"]
