import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '../globals.css';
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';
import Navbar from '@/components/global/Navbar';
import { ThemeProvider } from '@/theme/ThemeProvider';
import { SessionProvider } from '@/context/useSession';
import { Toaster } from '@/components/ui/sonner';
import { SelectedItemProvider } from '@/context/useSelected';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <SessionProvider>
                    <SelectedItemProvider>
                        <ThemeProvider attribute="class" defaultTheme="dark">
                            <Toaster />
                            <main className="grow min-h-screen">
                                {children}
                            </main>
                        </ThemeProvider>
                    </SelectedItemProvider>
                </SessionProvider>
            </body>
        </html>
    );
}
